package corbaBanque;


/**
* corbaBanque/IBanqueRemoteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banque.idl
* vendredi 29 novembre 2024 21 h 05 CET
*/

public interface IBanqueRemoteOperations 
{
  double conversion (double mt);
  corbaBanque.Compte getCompte (int code);
} // interface IBanqueRemoteOperations
