package corbaBanque;


/**
* corbaBanque/IBanqueRemote.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banque.idl
* vendredi 29 novembre 2024 21 h 05 CET
*/

public interface IBanqueRemote extends IBanqueRemoteOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IBanqueRemote
